# Mac shortcuts backed by tools and applications installed on this machine.
alias du='dust'
alias df='duf'
alias cat='bat'
alias diff='colordiff'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias mergepdf='gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=_merged.pdf'

alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias -- -='cd -'
alias github='cd "$HOME/projects/github"'
alias lhcb='cd "$HOME/projects/lhcb"'
alias cern='cd "$HOME/projects/cern"'
alias doc='cd "$HOME/Documents"'
alias ds='cd "$HOME/.ssh"'
alias dz='cd "$DOTFILES_ROOT"'
alias de='cd "$HOME/Desktop"'
alias dq='cd "$HOME/Downloads"'
alias dls='cd "$HOME/Library/Services"'

alias pycat='pygmentize -g'
alias record='asciinema rec'
alias hn='clx'
alias findgrep='GrePFind'
alias gen_pass='LC_ALL=C tr -dc "[:alnum:]" < /dev/urandom | head -c 20 | pbcopy'

alias firefox='open -a "/Applications/Firefox Developer Edition.app"'
alias orion='open -a "/Applications/Orion RC.app"'
alias web='firefox'
alias safari='open -a "/Applications/Safari.app"'
alias hidedesktop='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias showdesktop='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'
alias find_apps='mdfind kMDItemAppStoreHasReceipt=1'
alias badge='tput bel'
alias battery='pmset -g batt'

alias update='sudo softwareupdate -i -a; brew update; brew upgrade'
alias upgrade='brew upgrade'
alias clear_dns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias localip='ipconfig getifaddr en0'
alias ip6_on='sudo networksetup -setv6automatic Wi-Fi'
alias ip6_off='sudo networksetup -setv6off Wi-Fi'
alias bypass_xyz='dnscrypt-proxy -config "$HOME/.config/dnscrypt-proxy/dnscrypt-proxy.toml"'
